image: php:7.3.6
pipelines:
  default:
    - step:
        name: Test
        caches:
          - php-ext-source
          - php-ext
          - composer
        script:
          - apt-get update && apt-get install -qy git unzip libicu-dev
          - docker-php-ext-install intl
          - docker-php-ext-install bcmath
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ./vendor/bin/phpunit --verbose
definitions:
 caches:
    php-ext-source: /usr/src/php/ext
    php-ext: /usr/local/lib/php/extensions