image: php:7.3.6
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y git unzip libicu-dev
          - docker-php-ext-install intl
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit